import type {
  Budget,
  Category,
  CommercialDocument,
  Customer,
  CustomerAccountStatement,
  MoneyTransaction,
  Product,
  Supplier,
  TicketItem,
  Warehouse,
} from "./types"

export const products: Product[] = [
  {
    id: "p-40",
    code: "40",
    barcode: "7790895000997",
    name: "ACONCAGUA GIN VERDE LIMA Y LIMON 750C",
    categoryId: "cat-bebidas",
    subcategoryId: "sub-aconcagua",
    salePrice: 10931.08,
    discountPercent: 10,
    purchasePrice: 7420,
    stock: 18,
    active: true,
    handlesSerials: false,
    image:
      "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=640&q=80",
    type: "Producto",
    currency: "ARS",
    soldAs: "Mercaderia",
    vat: "21%",
    accountingAccount: "Ventas mercaderias",
    supplier: "Distribuidora Norte SA",
    presentation: "Botella 750 cc",
    unit: "Unidad",
    location: "Gondola B-04",
    afipConcept: "Productos",
    characteristics: { Acabado: "Vidrio", Color: "Verde" },
  },
  {
    id: "p-41",
    code: "41",
    barcode: "7790895643835",
    name: "ADES MANZANA X 1000",
    categoryId: "cat-jugos",
    subcategoryId: "sub-ades",
    salePrice: 1782.43,
    purchasePrice: 1160,
    stock: 7,
    active: true,
    handlesSerials: false,
    image:
      "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=640&q=80",
    type: "Producto",
    currency: "ARS",
    soldAs: "Mercaderia",
    vat: "21%",
    accountingAccount: "Ventas mercaderias",
    supplier: "Alimentos del Centro",
    presentation: "Unidad 1 L",
    unit: "Unidad",
    location: "Gondola A-02",
    afipConcept: "Productos",
    characteristics: { Sabor: "Manzana", Envase: "Tetra" },
  },
  {
    id: "p-70",
    code: "70",
    barcode: "7790123451000",
    name: "ANDES BLANCA X 1000",
    categoryId: "cat-cervezas",
    subcategoryId: "sub-andes",
    salePrice: 2126.05,
    discountPercent: 15,
    purchasePrice: 1410,
    stock: 2,
    active: true,
    handlesSerials: false,
    image:
      "https://images.unsplash.com/photo-1566633806327-68e152aaf26d?auto=format&fit=crop&w=640&q=80",
    type: "Producto",
    currency: "ARS",
    soldAs: "Mercaderia",
    vat: "21%",
    accountingAccount: "Ventas mercaderias",
    supplier: "Bebidas Cuyo SRL",
    presentation: "Unidad 1 L",
    unit: "Unidad",
    location: "Camara 1",
    afipConcept: "Productos",
    characteristics: { Estilo: "Blanca", Retornable: "Si" },
  },
  {
    id: "p-93",
    code: "93",
    barcode: "7799001301220",
    name: "BALANZA DIGITAL KRETZ NOVA",
    categoryId: "cat-equipamiento",
    subcategoryId: "sub-kretz",
    salePrice: 268000,
    purchasePrice: 201400,
    stock: 4,
    active: true,
    handlesSerials: true,
    type: "Producto seriado",
    currency: "ARS",
    soldAs: "Bien de uso",
    vat: "21%",
    accountingAccount: "Ventas equipamiento",
    supplier: "Kretz Argentina",
    presentation: "Unidad",
    unit: "Unidad",
    location: "Deposito principal",
    afipConcept: "Productos",
    characteristics: { Display: "LCD", Capacidad: "30 kg" },
  },
  {
    id: "p-218",
    code: "218",
    barcode: "7790000000218",
    name: "SERVICIO MANTENIMIENTO BALANZA",
    categoryId: "cat-servicios",
    subcategoryId: "sub-mantenimiento",
    salePrice: null,
    purchasePrice: 0,
    stock: 0,
    active: true,
    handlesSerials: false,
    type: "Servicio",
    currency: "ARS",
    soldAs: "Servicio",
    vat: "21%",
    accountingAccount: "Servicios tecnicos",
    supplier: "Servicio interno",
    presentation: "Servicio tecnico",
    unit: "Servicio",
    location: "No aplica",
    afipConcept: "Servicios",
    characteristics: { Modalidad: "En local" },
  },
  {
    id: "p-302",
    code: "302",
    barcode: "7799001300302",
    name: "LECTOR CODIGO DE BARRAS USB",
    categoryId: "cat-equipamiento",
    subcategoryId: "sub-tecno-pos",
    salePrice: 84990,
    discountPercent: 8,
    purchasePrice: 62300,
    stock: 0,
    active: false,
    handlesSerials: true,
    type: "Producto seriado",
    currency: "ARS",
    soldAs: "Bien de uso",
    vat: "21%",
    accountingAccount: "Ventas equipamiento",
    supplier: "Tecno POS SA",
    presentation: "Caja",
    unit: "Unidad",
    location: "Deposito 2",
    afipConcept: "Productos",
    characteristics: { Conexion: "USB", Lectura: "1D/2D" },
  },
  {
    id: "p-305",
    code: "305",
    barcode: "7799001300305",
    name: "ROLLO TERMICO 80 X 80",
    categoryId: "cat-libreria",
    subcategoryId: "sub-consumibles",
    salePrice: 2350,
    purchasePrice: 1380,
    stock: 42,
    active: true,
    handlesSerials: false,
    type: "Producto",
    currency: "ARS",
    soldAs: "Mercaderia",
    vat: "21%",
    accountingAccount: "Ventas mercaderias",
    supplier: "Papelera Federal",
    presentation: "Unidad",
    unit: "Unidad",
    location: "Estante C-10",
    afipConcept: "Productos",
    characteristics: { Ancho: "80 mm", Diametro: "80 mm" },
  },
  {
    id: "p-310",
    code: "310",
    barcode: "7799001300310",
    name: "BOLSA CAMISETA MEDIANA",
    categoryId: "cat-embalaje",
    subcategoryId: "sub-bolsas",
    salePrice: 120,
    purchasePrice: 58,
    stock: 360,
    active: true,
    handlesSerials: false,
    type: "Producto",
    currency: "ARS",
    soldAs: "Mercaderia",
    vat: "21%",
    accountingAccount: "Ventas mercaderias",
    supplier: "Pack Norte",
    presentation: "Unidad",
    unit: "Unidad",
    location: "Caja",
    afipConcept: "Productos",
    characteristics: { Tamano: "Mediana", Color: "Blanca" },
  },
]

const audit = {
  createdBy: "admin",
  createdAt: "2026-07-22T20:00:00-03:00",
}

export const categories: Category[] = [
  {
    id: "cat-cervezas",
    code: "1",
    name: "Cerveza",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-andes", categoryId: "cat-cervezas", code: "1", name: "Andes", active: true, articleCount: 1 },
      { id: "sub-brahma", categoryId: "cat-cervezas", code: "2", name: "Brahma", active: true, articleCount: 0 },
      { id: "sub-budweiser", categoryId: "cat-cervezas", code: "3", name: "Budweiser", active: true, articleCount: 0 },
      { id: "sub-corona", categoryId: "cat-cervezas", code: "4", name: "Corona", active: true, articleCount: 0 },
      { id: "sub-heineken", categoryId: "cat-cervezas", code: "5", name: "Heineken", active: true, articleCount: 0 },
    ],
  },
  {
    id: "cat-bebidas",
    code: "2",
    name: "Bebidas espirituosas",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-aconcagua", categoryId: "cat-bebidas", code: "1", name: "Aconcagua", active: true, articleCount: 1 },
      { id: "sub-fernet", categoryId: "cat-bebidas", code: "2", name: "Fernet", active: true, articleCount: 0 },
    ],
  },
  {
    id: "cat-jugos",
    code: "3",
    name: "Jugos",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-ades", categoryId: "cat-jugos", code: "1", name: "Ades", active: true, articleCount: 1 },
    ],
  },
  {
    id: "cat-equipamiento",
    code: "4",
    name: "Equipamiento",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 2,
    audit,
    subcategories: [
      { id: "sub-kretz", categoryId: "cat-equipamiento", code: "1", name: "Kretz", active: true, articleCount: 1 },
      { id: "sub-tecno-pos", categoryId: "cat-equipamiento", code: "2", name: "Tecno POS", active: true, articleCount: 1 },
    ],
  },
  {
    id: "cat-servicios",
    code: "5",
    name: "Servicios",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-mantenimiento", categoryId: "cat-servicios", code: "1", name: "Mantenimiento", active: true, articleCount: 1 },
    ],
  },
  {
    id: "cat-libreria",
    code: "6",
    name: "Libreria",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-consumibles", categoryId: "cat-libreria", code: "1", name: "Consumibles", active: true, articleCount: 1 },
    ],
  },
  {
    id: "cat-embalaje",
    code: "7",
    name: "Embalaje",
    active: true,
    directArticleCount: 0,
    totalArticleCount: 1,
    audit,
    subcategories: [
      { id: "sub-bolsas", categoryId: "cat-embalaje", code: "1", name: "Bolsas", active: true, articleCount: 1 },
    ],
  },
]

export const customers: Customer[] = [
  {
    id: "c-1",
    code: "000001",
    name: "Consumidor Final",
    documentType: "DNI",
    document: "",
    vatCategory: "Consumidor final",
    saleCondition: "Efectivo",
    taxTreatment: "Exento",
    priceList: "Publico",
    phone: "",
    email: "",
    address: "",
    active: true,
  },
  {
    id: "c-2",
    code: "000184",
    name: "Almacen San Martin SRL",
    documentType: "CUIT",
    document: "30-71624518-9",
    vatCategory: "Responsable inscripto",
    saleCondition: "Cuenta corriente",
    taxTreatment: "Con impuestos",
    priceList: "Mayorista",
    phone: "381 455-0190",
    email: "compras@almacensanmartin.com",
    address: "San Martin 1220, San Miguel de Tucuman",
    active: true,
  },
  {
    id: "c-3",
    code: "000241",
    name: "Maria Elena Paz",
    documentType: "CUIL",
    document: "27-28459210-4",
    vatCategory: "Consumidor final",
    saleCondition: "Efectivo",
    taxTreatment: "Exento",
    priceList: "Publico",
    phone: "381 612-3041",
    email: "maria.paz@example.com",
    address: "Laprida 540, Yerba Buena",
    active: true,
  },
  {
    id: "c-4",
    code: "000310",
    name: "Servicios Industriales NOA SA",
    documentType: "CUIT",
    document: "30-70983211-7",
    vatCategory: "Responsable inscripto",
    saleCondition: "Cuenta corriente",
    taxTreatment: "Con impuestos",
    priceList: "Corporativa",
    phone: "381 421-7780",
    email: "administracion@sinoa.com.ar",
    address: "Parque Industrial Tucuman, Lote 14",
    active: false,
  },
]

export const budgets: Budget[] = [
  {
    id: "budget-128",
    number: "P-0004-00000128",
    internalNumber: "PR-128",
    date: "2026-07-22",
    destination: "Mostrador",
    pointOfSale: "PV 0004",
    letter: "X",
    cc: "1",
    validity: "No confirmado · demo",
    customerId: "c-2",
    customerName: "Almacen San Martin SRL",
    customerTaxId: "30-71624518-9",
    seller: "Sofía Romero",
    priceList: "Mayorista",
    saleCondition: "Cuenta corriente",
    currency: "ARS",
    purchaseOrder: "OC-1458",
    shift: "Mañana",
    observations: "Entrega coordinada con el cliente.",
    lines: [
      {
        id: "budget-128-line-1",
        productId: "p-40",
        code: "541",
        description: "IMPERIAL GOLDEN LATAS X 473",
        unit: "BULTO X24",
        unitCount: 1,
        quantity: 24,
        basePrice: 1061.05,
        manualDiscount: 0,
        promotionalDiscount: 0,
        discountPercent: 0,
        finalPrice: 1061.05,
        vatRate: 21,
        vatType: "G · demo",
        priceWithVat: 1283.872,
        priceList: "Mayorista",
        deliveryDate: "2026-07-22",
        amount: 30812.92,
      },
    ],
    totals: {
      net: 25465.23,
      bonus: 0,
      vat105: 0,
      vat21: 5347.7,
      vat27: 0,
      otherPerceptions: 0,
      total: 30812.92,
    },
    annulled: false,
    audit: { createdBy: "Sofía Romero", createdAt: "22/07/2026 19:42" },
  },
  {
    id: "budget-127",
    number: "P-0004-00000127",
    internalNumber: "PR-127",
    date: "2026-07-20",
    destination: "Entrega",
    pointOfSale: "PV 0004",
    letter: "X",
    cc: "1",
    validity: "Vigencia 15 días · demo",
    customerId: "c-4",
    customerName: "Servicios Industriales NOA SA",
    customerTaxId: "30-70983211-7",
    seller: "Marcos Díaz",
    priceList: "Corporativa",
    saleCondition: "Cuenta corriente",
    currency: "ARS",
    purchaseOrder: "",
    shift: "Tarde",
    observations: "",
    lines: [
      {
        id: "budget-127-line-1",
        productId: "p-93",
        code: "93",
        description: "BALANZA DIGITAL KRETZ NOVA",
        unit: "Unidad",
        unitCount: 1,
        quantity: 1,
        basePrice: 221487.6,
        manualDiscount: 0,
        promotionalDiscount: 0,
        discountPercent: 0,
        finalPrice: 221487.6,
        vatRate: 21,
        vatType: "G · demo",
        priceWithVat: 268000,
        priceList: "Corporativa",
        deliveryDate: "2026-07-25",
        amount: 268000,
      },
    ],
    totals: { net: 221487.6, bonus: 0, vat105: 0, vat21: 46512.4, vat27: 0, otherPerceptions: 0, total: 268000 },
    annulled: false,
    invoicedRelation: "Factura A 0004-00001810 · dato simulado",
    audit: { createdBy: "Marcos Díaz", createdAt: "20/07/2026 14:20" },
  },
  {
    id: "budget-126",
    number: "P-0004-00000126",
    internalNumber: "PR-126",
    date: "2026-07-15",
    destination: "Mostrador",
    pointOfSale: "PV 0004",
    letter: "X",
    cc: "1",
    validity: "Sin confirmar · demo",
    customerId: "c-3",
    customerName: "Maria Elena Paz",
    customerTaxId: "27-28459210-4",
    seller: "Lucía Fernández",
    priceList: "Publico",
    saleCondition: "Efectivo",
    currency: "ARS",
    purchaseOrder: "",
    shift: "",
    observations: "Presupuesto anulado de muestra.",
    lines: [],
    totals: { net: 0, bonus: 0, vat105: 0, vat21: 0, vat27: 0, otherPerceptions: 0, total: 0 },
    annulled: true,
    audit: { createdBy: "Lucía Fernández", createdAt: "15/07/2026 10:18" },
  },
  {
    id: "budget-104",
    number: "P-0004-00000104",
    internalNumber: "PR-104",
    date: "2026-05-03",
    destination: "Mostrador",
    pointOfSale: "PV 0004",
    letter: "X",
    cc: "1",
    validity: "Vigencia vencida · demo",
    customerId: "c-1",
    customerName: "Consumidor Final",
    customerTaxId: "Sin identificación fiscal",
    seller: "Sofía Romero",
    priceList: "Publico",
    saleCondition: "Efectivo",
    currency: "ARS",
    purchaseOrder: "",
    shift: "",
    observations: "",
    lines: [],
    totals: { net: 14462.81, bonus: 0, vat105: 0, vat21: 3037.19, vat27: 0, otherPerceptions: 0, total: 17500 },
    annulled: false,
    audit: { createdBy: "Sofía Romero", createdAt: "03/05/2026 09:12" },
  },
]

export const customerAccountStatements: CustomerAccountStatement[] = [
  {
    customerId: "c-2",
    movementCount: 5,
    pesifiedBalance: 39307.67,
    presentationCurrency: "ARS",
    queriedAt: "22/07/2026 16:18 · datos simulados",
    currencyGroups: [
      {
        currencyCode: "ARS",
        currencyLabel: "Peso argentino",
        debitTotal: 101211.61,
        creditTotal: 61903.94,
        runningBalanceTotal: 39307.67,
        movements: [
          {
            id: "account-c2-opening",
            paymentIndicator: "—",
            companyLabel: "Casa Central",
            date: "2026-06-21",
            concept: "Saldo anterior",
            technicalCode: "{P}",
            number: "0",
            days: null,
            debit: 82300,
            credit: 0,
            runningBalance: 82300,
            currencyCode: "ARS",
          },
          {
            id: "account-c2-invoice",
            paymentIndicator: "—",
            companyLabel: "Casa Central",
            date: "2026-07-22",
            concept: "Factura A",
            number: "0004-00001842",
            days: 0,
            debit: 18911.61,
            credit: 0,
            runningBalance: 101211.61,
            currencyCode: "ARS",
            sourceType: "document",
            sourceId: "sale-invoice-1842",
          },
          {
            id: "account-c2-receipt",
            paymentIndicator: "Sí",
            companyLabel: "Casa Central",
            date: "2026-07-22",
            concept: "Recibo",
            number: "RC-0004-009041",
            days: 0,
            debit: 0,
            credit: 50000,
            runningBalance: 51211.61,
            currencyCode: "ARS",
            sourceType: "receipt",
            sourceId: "receipt-9041",
          },
          {
            id: "account-c2-credit-note",
            paymentIndicator: "—",
            companyLabel: "Casa Central",
            date: "2026-07-21",
            concept: "Nota de crédito A",
            number: "0004-00000217",
            days: 1,
            debit: 0,
            credit: 11903.94,
            runningBalance: 39307.67,
            currencyCode: "ARS",
            sourceType: "document",
            sourceId: "sale-credit-217",
          },
          {
            id: "account-c2-delivery",
            paymentIndicator: "—",
            companyLabel: "Sucursal Centro",
            date: "2026-07-18",
            concept: "Remito informativo · demo",
            number: "R-0007-00003210",
            days: 4,
            debit: 0,
            credit: 0,
            runningBalance: 39307.67,
            currencyCode: "ARS",
            sourceType: "delivery-note",
            sourceId: "sale-delivery-3210",
          },
        ],
      },
    ],
  },
  {
    customerId: "c-3",
    movementCount: 0,
    pesifiedBalance: 0,
    presentationCurrency: "ARS",
    queriedAt: "22/07/2026 16:18 · datos simulados",
    currencyGroups: [],
  },
  {
    customerId: "c-4",
    movementCount: 2,
    pesifiedBalance: 214500,
    presentationCurrency: "ARS",
    queriedAt: "22/07/2026 16:18 · datos simulados",
    currencyGroups: [
      {
        currencyCode: "ARS",
        currencyLabel: "Peso argentino",
        debitTotal: 274500,
        creditTotal: 60000,
        runningBalanceTotal: 214500,
        movements: [
          {
            id: "account-c4-opening",
            paymentIndicator: "—",
            companyLabel: "Casa Central",
            date: "2026-06-21",
            concept: "Saldo anterior",
            technicalCode: "{P}",
            number: "0",
            days: null,
            debit: 274500,
            credit: 0,
            runningBalance: 274500,
            currencyCode: "ARS",
          },
          {
            id: "account-c4-receipt",
            paymentIndicator: "Sí",
            companyLabel: "Casa Central",
            date: "2026-07-10",
            concept: "Recibo",
            number: "RC-0004-009038",
            days: 12,
            debit: 0,
            credit: 60000,
            runningBalance: 214500,
            currencyCode: "ARS",
            sourceType: "receipt",
            sourceId: "receipt-9038",
          },
        ],
      },
    ],
  },
]

export const suppliers: Supplier[] = [
  {
    id: "s-1",
    code: "P-0012",
    name: "Distribuidora Norte SA",
    cuit: "30-61233018-2",
    vatCategory: "Responsable inscripto",
    phone: "381 430-0091",
    email: "pedidos@distrinorte.com",
    active: true,
    accountingAccount: "Proveedores mercaderias",
    expenseAccount: "Compras para reventa",
    retentionCategory: "Ganancias - Bienes",
    taxTreatment: "Con impuestos",
    address: "Ruta 9 km 1284, Tucuman",
  },
  {
    id: "s-2",
    code: "P-0037",
    name: "Monotributo Servicios Ruiz",
    cuit: "20-24810943-6",
    vatCategory: "Monotributista",
    phone: "381 544-2190",
    email: "serviciosruiz@example.com",
    active: true,
    accountingAccount: "Proveedores servicios",
    expenseAccount: "Mantenimiento",
    retentionCategory: "No aplica",
    taxTreatment: "Exento",
    address: "Av. Belgrano 2140, Tucuman",
  },
  {
    id: "s-3",
    code: "P-0049",
    name: "Papelera Federal SRL",
    cuit: "30-69871002-1",
    vatCategory: "Responsable inscripto",
    phone: "011 4545-1820",
    email: "ventas@papelerafederal.com.ar",
    active: true,
    accountingAccount: "Proveedores mercaderias",
    expenseAccount: "Insumos de venta",
    retentionCategory: "IIBB Convenio Multilateral",
    taxTreatment: "Con impuestos",
    address: "Constituyentes 3840, CABA",
  },
]

export const commercialDocuments: CommercialDocument[] = [
  {
    id: "purchase-invoice-1842",
    context: "purchase",
    family: "invoice",
    typeLabel: "Factura A",
    date: "2026-07-22",
    number: "0003-00001842",
    partyName: "Distribuidora Norte SA",
    partyTaxId: "30-61233018-2",
    subtotal: 128040,
    taxes: 26888.4,
    total: 154928.4,
    currency: "ARS",
    status: "Registrada · demo",
    pointOfSale: "PV 0003",
    fiscalState: "Estado de ejemplo",
    items: [
      { id: "pi-1842-1", code: "40", description: "Aconcagua Gin 750 cc", quantity: 6, unitPrice: 7420, vatRate: 21 },
      { id: "pi-1842-2", code: "70", description: "Andes Blanca 1 L", quantity: 24, unitPrice: 1410, vatRate: 21 },
      { id: "pi-1842-3", code: "305", description: "Rollo térmico 80 x 80", quantity: 36, unitPrice: 1380, vatRate: 21 },
    ],
    audit: { createdBy: "María Sosa", createdAt: "22/07/2026 09:18" },
  },
  {
    id: "purchase-credit-216",
    context: "purchase",
    family: "credit-note",
    typeLabel: "Nota de crédito A",
    date: "2026-07-21",
    number: "0003-00000216",
    partyName: "Distribuidora Norte SA",
    partyTaxId: "30-61233018-2",
    subtotal: 14840,
    taxes: 3116.4,
    total: 17956.4,
    currency: "ARS",
    status: "Aplicada · demo",
    relatedDocument: "Factura A 0003-00001842",
    pointOfSale: "PV 0003",
    items: [
      { id: "pc-216-1", code: "40", description: "Aconcagua Gin 750 cc", quantity: 2, unitPrice: 7420, vatRate: 21 },
    ],
    audit: { createdBy: "María Sosa", createdAt: "21/07/2026 16:42", updatedBy: "Lucía Fernández", updatedAt: "21/07/2026 16:49" },
  },
  {
    id: "purchase-debit-88",
    context: "purchase",
    family: "debit-note",
    typeLabel: "Nota de débito A",
    date: "2026-07-18",
    number: "0003-00000088",
    partyName: "Papelera Federal SRL",
    partyTaxId: "30-69871002-1",
    subtotal: 4400,
    taxes: 924,
    total: 5324,
    currency: "ARS",
    status: "Pendiente · demo",
    relatedDocument: "Factura A 0006-00000971",
    pointOfSale: "PV 0003",
    items: [
      { id: "pd-88-1", code: "AJ", description: "Ajuste comercial de ejemplo", quantity: 1, unitPrice: 4400, vatRate: 21 },
    ],
    audit: { createdBy: "Carlos Molina", createdAt: "18/07/2026 11:07" },
  },
  {
    id: "purchase-delivery-9021",
    context: "purchase",
    family: "delivery-note",
    typeLabel: "Remito",
    date: "2026-07-17",
    number: "R-0003-00009021",
    partyName: "Papelera Federal SRL",
    partyTaxId: "30-69871002-1",
    subtotal: 49680,
    taxes: 0,
    total: 49680,
    currency: "ARS",
    status: "Recibido · demo",
    pointOfSale: "Depósito principal",
    items: [
      { id: "pr-9021-1", code: "305", description: "Rollo térmico 80 x 80", quantity: 36, unitPrice: 1380, vatRate: 0 },
    ],
    audit: { createdBy: "Carlos Molina", createdAt: "17/07/2026 08:35" },
  },
  {
    id: "sale-invoice-1842",
    context: "sale",
    family: "invoice",
    typeLabel: "Factura A",
    date: "2026-07-22",
    number: "0004-00001842",
    partyName: "Almacén San Martín SRL",
    partyTaxId: "30-71624518-9",
    subtotal: 15629.43,
    taxes: 3282.18,
    total: 18911.61,
    currency: "ARS",
    status: "Emitida · demo",
    pointOfSale: "PV 0004",
    fiscalState: "ARCA · ejemplo",
    items: [
      { id: "si-1842-1", code: "40", description: "Aconcagua Gin 750 cc", quantity: 1, unitPrice: 9837.97, vatRate: 21 },
      { id: "si-1842-2", code: "41", description: "Ades Manzana x 1000", quantity: 2, unitPrice: 1693.31, vatRate: 21 },
      { id: "si-1842-3", code: "305", description: "Rollo térmico 80 x 80", quantity: 1, unitPrice: 2404.84, vatRate: 21 },
    ],
    audit: { createdBy: "Sofía Romero", createdAt: "22/07/2026 10:26" },
  },
  {
    id: "sale-credit-217",
    context: "sale",
    family: "credit-note",
    typeLabel: "Nota de crédito A",
    date: "2026-07-21",
    number: "0004-00000217",
    partyName: "Almacén San Martín SRL",
    partyTaxId: "30-71624518-9",
    subtotal: 9837.97,
    taxes: 2065.97,
    total: 11903.94,
    currency: "ARS",
    status: "Emitida · demo",
    relatedDocument: "Factura A 0004-00001842",
    pointOfSale: "PV 0004",
    fiscalState: "ARCA · ejemplo",
    items: [
      { id: "sc-217-1", code: "40", description: "Aconcagua Gin 750 cc", quantity: 1, unitPrice: 9837.97, vatRate: 21 },
    ],
    audit: { createdBy: "Sofía Romero", createdAt: "21/07/2026 17:02" },
  },
  {
    id: "sale-debit-89",
    context: "sale",
    family: "debit-note",
    typeLabel: "Nota de débito A",
    date: "2026-07-19",
    number: "0004-00000089",
    partyName: "Servicios Industriales NOA SA",
    partyTaxId: "30-70983211-7",
    subtotal: 6200,
    taxes: 1302,
    total: 7502,
    currency: "ARS",
    status: "Borrador · demo",
    relatedDocument: "Factura A 0004-00001810",
    pointOfSale: "PV 0004",
    items: [
      { id: "sd-89-1", code: "AJ", description: "Ajuste comercial de ejemplo", quantity: 1, unitPrice: 6200, vatRate: 21 },
    ],
    audit: { createdBy: "Lucía Fernández", createdAt: "19/07/2026 14:11" },
  },
  {
    id: "sale-delivery-412",
    context: "sale",
    family: "delivery-note",
    typeLabel: "Remito",
    date: "2026-07-16",
    number: "R-0004-00000412",
    partyName: "Servicios Industriales NOA SA",
    partyTaxId: "30-70983211-7",
    subtotal: 268000,
    taxes: 0,
    total: 268000,
    currency: "ARS",
    status: "Entregado · demo",
    pointOfSale: "PV 0004",
    items: [
      { id: "sr-412-1", code: "93", description: "Balanza digital Kretz Nova", quantity: 1, unitPrice: 268000, vatRate: 0 },
    ],
    audit: { createdBy: "Marcos Díaz", createdAt: "16/07/2026 12:30" },
  },
]

export const moneyTransactions: MoneyTransaction[] = [
  {
    id: "payment-1284",
    context: "payment",
    date: "2026-07-22",
    number: "OP-0003-00001284",
    partyName: "Distribuidora Norte SA",
    partyTaxId: "30-61233018-2",
    total: 154928.4,
    currency: "ARS",
    detail: "Cancelación de factura de compra",
    status: "Registrada · demo",
    relatedDocument: "Factura A 0003-00001842",
    location: "Casa Central",
    audit: { createdBy: "María Sosa", createdAt: "22/07/2026 12:18" },
  },
  {
    id: "payment-1283",
    context: "payment",
    date: "2026-07-19",
    number: "OP-0003-00001283",
    partyName: "Papelera Federal SRL",
    partyTaxId: "30-69871002-1",
    total: 49680,
    currency: "ARS",
    detail: "Pago parcial · ejemplo",
    status: "Borrador · demo",
    relatedDocument: "Factura A 0006-00000971",
    location: "Casa Central",
    audit: { createdBy: "Carlos Molina", createdAt: "19/07/2026 09:42" },
  },
  {
    id: "payment-1282",
    context: "payment",
    date: "2026-07-15",
    number: "OP-0007-00001282",
    partyName: "Servicios Industriales NOA SA",
    partyTaxId: "30-70983211-7",
    total: 87500,
    currency: "ARS",
    detail: "Pago a cuenta · ejemplo",
    status: "Registrada · demo",
    location: "Sucursal Centro",
    audit: { createdBy: "Lucía Fernández", createdAt: "15/07/2026 16:05" },
  },
  {
    id: "receipt-9041",
    context: "receipt",
    date: "2026-07-22",
    number: "RC-0004-00009041",
    partyName: "Almacén San Martín SRL",
    partyTaxId: "30-71624518-9",
    total: 18911.61,
    currency: "ARS",
    detail: "Cobro de factura de venta",
    status: "Emitido · demo",
    relatedDocument: "Factura A 0004-00001842",
    location: "Casa Central",
    audit: { createdBy: "Sofía Romero", createdAt: "22/07/2026 11:06" },
  },
  {
    id: "receipt-9040",
    context: "receipt",
    date: "2026-07-20",
    number: "RC-0004-00009040",
    partyName: "Servicios Industriales NOA SA",
    partyTaxId: "30-70983211-7",
    total: 7502,
    currency: "ARS",
    detail: "Cobro parcial · ejemplo",
    status: "Borrador · demo",
    relatedDocument: "Factura A 0004-00001810",
    location: "Casa Central",
    audit: { createdBy: "Marcos Díaz", createdAt: "20/07/2026 14:22" },
  },
  {
    id: "receipt-9039",
    context: "receipt",
    date: "2026-07-14",
    number: "RC-0007-00009039",
    partyName: "Consumidor Final",
    partyTaxId: "Sin identificación fiscal",
    total: 32600,
    currency: "ARS",
    detail: "Recibo administrativo · ejemplo",
    status: "Emitido · demo",
    location: "Sucursal Centro",
    audit: { createdBy: "Lucía Fernández", createdAt: "14/07/2026 10:18" },
  },
]

export const warehouses: Warehouse[] = [
  {
    id: "w-1",
    code: "DEP-01",
    name: "Deposito principal",
    type: "ORIGEN",
    company: "InfoManager Demo SA",
    pointOfSale: "Casa Central - PV 0004",
    address: "Av. Aconquija 1840, Yerba Buena",
    costCenter: "Stock central",
  },
  {
    id: "w-2",
    code: "DEP-02",
    name: "Salon de ventas",
    type: "DESTINO",
    company: "InfoManager Demo SA",
    pointOfSale: "Casa Central - PV 0004",
    address: "Av. Aconquija 1840, Yerba Buena",
    costCenter: "Ventas local",
  },
  {
    id: "w-3",
    code: "DEP-03",
    name: "Sucursal Centro",
    type: "DESTINO",
    company: "InfoManager Demo SA",
    pointOfSale: "Sucursal Centro - PV 0007",
    address: "San Martin 780, San Miguel de Tucuman",
    costCenter: "Sucursal Centro",
  },
]

export const initialTicket: TicketItem[] = [
  {
    id: "t-1",
    productId: "p-40",
    quantity: 1,
    manualDiscount: 0,
    promotionalDiscount: 0,
  },
  {
    id: "t-2",
    productId: "p-41",
    quantity: 2,
    manualDiscount: 0,
    promotionalDiscount: 5,
  },
  {
    id: "t-3",
    productId: "p-305",
    quantity: 3,
    manualDiscount: 0,
    promotionalDiscount: 0,
  },
]

export const favoriteProductIds = [
  "p-40",
  "p-41",
  "p-70",
  "p-93",
  "p-305",
  "p-310",
  "p-218",
  "p-302",
]

export const sellers = ["Sofia Romero", "Marcos Diaz", "Lucia Fernandez"]

export const paymentMethods = [
  "Efectivo",
  "Tarjeta",
  "Transferencia",
  "Mercado Pago",
  "PayWay",
] as const

export function money(value: number | null) {
  if (value === null) return "Sin precio"
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    maximumFractionDigits: 2,
  }).format(value)
}
